theme: jekyll-theme-architect

title: [First Cup of Jakarta EE Tutorial]
description: [First Cup of Jakarta EE Tutorial Project]

# sidebar links url
links:
  source: https://github.com/javaee/firstcup
  download: https://github.com/javaee/firstcup/releases
  #mailinglist: https://javaee.groups.io/g/tutorial
  #javadocs:
  docs: https://javaee.github.io/firstcup/toc.html
  #faq:

