remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [First Cup of Jakarta EE Tutorial]
description: [First Cup of Jakarta EE Tutorial Project]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/glassfish-firstcup
  download: https://github.com/eclipse-ee4j/glassfish-firstcup/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/glassfish-dev
  #javadocs:
  docs: toc.html
  #faq:

include:
  - LICENSE.md
  - CONTRIBUTING.md
